- main.py
> Added error highlighting

- README.md
- sample_cities/ZZZ_template_city/source_data/met_files/source_files/README.md
> preparation for demo

- README.md
- main.py
- sample_cities/README.md
- sample_cities/ZZZ_template_city/.config_method_parameters.yml
- sample_cities/ZZZ_template_city/README.md
- sample_cities/ZZZ_template_city/source_data/met_files/met_template.txt
- workers/city_data.py
- workers/umep_plugin_processor.py
> Modifications following first demo

- README.md
- job_handler/reporter.py
- main.py
- tile_processor.py
> fixed bugs and updated readme

- setup_conda.bat
- test/test_processing_runs_integration_tests.py
> Fixed path errors

- .gitignore
- README.md
- job_handler/config_validator.py
- main.py
- sample_cities/ZAF_Capetown_small_tile/_run_CTCM_pre_check.bat
- sample_cities/ZAF_Capetown_small_tile/_run_CTCM_processing.bat
- sample_cities/ZZZ_template_city/_run_CTCM_pre_check.bat
- sample_cities/ZZZ_template_city/_run_CTCM_processing.bat
- test/test_processing_runs_integration_tests.py
- workers/job_manager.py
- workers/qgis_initializer.py
- workers/source_cif_data_downloader.py
- workers/tile_processor.py
- workers/umep_plugin_processor.py
> Cif 295 get cif notebook running on windows qgis server

- sample_cities/NLD_Amsterdam/.config_method_parameters.yml
- test/test_processing_runs_integration_tests.py
- worker_manager/config_validator.py
- worker_manager/graph_builder.py
> fixed bugs

- support/qgis_viewer/template_viewer.qgs
- support/qgis_viewer/vrt_files/template_wallaspect_0_0.vrt
- support/qgis_viewer/vrt_files/template_wallheight_0_0.vrt
- worker_manager/ancillary_files.py
- workers/city_data.py
Added wall aspect/height to qgis viewer
> Added wall aspect/height to qgis viewer

- support/qgis_viewer/template_viewer.qgs
> updated qgis viewer for tile_grid

- support/qgis_viewer/template_viewer.qgs
> further refined qgis file

- worker_manager/config_validator.py
added detection of null no_data value
> Cif 288 implement quality evaluation for solweig modeling

- worker_manager/config_validator.py
> added validation of band value range

- main.py
- worker_manager/config_validator.py
> Refined runtime prediction

- main.py
- worker_manager/job_manager.py
- workers/city_data.py
- workers/source_cif_data_downloader.py
- workers/tile_processor.py
- workers/worker_tools.py
> Added cleanup of primary_source_data for cif-only runs

- data/sample_cities/NLD_Amsterdam/.config_method_parameters.yml
- data/sample_cities/XXX_Invalid_city_1/.config_method_parameters.yml
- data/sample_cities/XXX_Invalid_city_2/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_cif_download_only/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_full_cif/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_small_mixed_cif/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_small_tile/.config_method_parameters.yml
- data/sample_cities/ZZZ_template_city/.config_method_parameters.yml
- src/workers/city_data.py
- src/workers/config_processor.py
> added latitude-based leave start/end

- main.py
> Updated time estimate

- src/worker_manager/config_validator.py
> Removed highlighted print since it does render correctly on EC2

- main.py
- src/data_validation/manager.py
- src/worker_manager/ancillary_files.py
- src/worker_manager/graph_builder.py
- src/worker_manager/job_manager.py
- src/workers/source_cif_data_downloader.py
- src/workers/umep_plugin_processor.py
- src/workers/worker_tile_processor.py
- test/test_ancillary_writers.py
- test/test_umep_processing.py
tested locally. 
Change improved performance of integration tests from 12 minutes to 8 minutes.
> Cif 320 support multiple scenarios for thermal comfort modeling

- src/constants.py
- src/worker_manager/ancillary_files.py
- src/workers/city_data.py
- src/workers/config_processor.py
- src/workers/source_cif_data_downloader.py
> Standardized names of primary data.

- ReleaseNotes.md
- src/data_validation/custom_primary_validator.py
> Adding release notes

- data/sample_cities/ZAF_Capetown_full_cif/.config_method_parameters.yml
- src/workers/worker_meteorological_processor.py
bug https://gfw.atlassian.net/browse/CDB-276 
- [ x] No
tested on local laptop
> fixed bug and improved error reporting message

- src/workers/worker_meteorological_processor.py
> improved era5 loop

- ReleaseNotes.md
https://gfw.atlassian.net/browse/CDB-299
> Cdb 299 write ctcm metadata to output file prior to run

- src/workers/umep_plugin_processor.py
> exclude temp directories and files from metadata

- data/sample_cities/NLD_Amsterdam/.config_method_parameters.yml
- data/sample_cities/NLD_Amsterdam_buffered/.config_method_parameters.yml
- data/sample_cities/NLD_Amsterdam_custom_tiled/.config_method_parameters.yml
- data/sample_cities/USA_Portland_small/.config_method_parameters.yml
- data/sample_cities/XXX_Invalid_city_1/.config_method_parameters.yml
- data/sample_cities/XXX_Invalid_city_2/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_cif_download_only/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_full_cif/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_small_mixed_cif/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_small_tile/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_with_full_intermediates/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_with_mixed_intermediates/.config_method_parameters.yml
- data/sample_cities/ZZZ_template_city/.config_method_parameters.yml
- src/workers/city_data.py
see https://gfw.atlassian.net/browse/CDB-300
> updating leaf on/of days

- ReleaseNotes.md
- data/sample_cities/NLD_Amsterdam/.config_method_parameters.yml
- data/sample_cities/NLD_Amsterdam_buffered/.config_method_parameters.yml
- data/sample_cities/NLD_Amsterdam_custom_tiled/.config_method_parameters.yml
- data/sample_cities/USA_Portland_small/.config_method_parameters.yml
- data/sample_cities/XXX_Invalid_city_1/.config_method_parameters.yml
- data/sample_cities/XXX_Invalid_city_2/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_cif_download_only/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_full_cif/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_small_mixed_cif/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_small_tile/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_with_full_intermediates/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_with_mixed_intermediates/.config_method_parameters.yml
- data/sample_cities/ZZZ_template_city/.config_method_parameters.yml
- data/support/update_config_method_parameters_yml.py
- src/data_validation/aoi_evaluator.py
- src/data_validation/custom_primary_validator.py
- src/worker_manager/graph_builder.py
- src/workers/worker_tile_processor.py
- tests/test_umep_processing.py
> improved buffer handling

- ReleaseNotes.md
- src/workers/source_cif_data_downloader.py
tested locally.
https://gfw.atlassian.net/browse/CDB-310
> replaced NasaDEM with FabDEM

- ReleaseNotes.md
- src/worker_manager/graph_builder.py
See https://gfw.atlassian.net/browse/CDB-321
> expanded tiles to outermost dimensions of AOI

- ReleaseNotes.md
- data/sample_cities/BRA_Rio_de_Janeiro_full_cif/.config_method_parameters.yml
- data/sample_cities/NLD_Amsterdam/.config_method_parameters.yml
- data/sample_cities/NLD_Amsterdam_buffered/.config_method_parameters.yml
- data/sample_cities/NLD_Amsterdam_custom_tiled/.config_method_parameters.yml
- data/sample_cities/USA_Portland_small/.config_method_parameters.yml
- data/sample_cities/XXX_Invalid_city_1/.config_method_parameters.yml
- data/sample_cities/XXX_Invalid_city_2/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_cif_download_only/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_full_cif/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_small_mixed_cif/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_small_tile/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_with_full_intermediates/.config_method_parameters.yml
- data/sample_cities/ZAF_Capetown_with_mixed_intermediates/.config_method_parameters.yml
- data/sample_cities/ZZZ_template_city/.config_method_parameters.yml
- data/support/update_config_method_parameters_yml.py
- src/data_validation/aoi_evaluator.py
- src/workers/city_data.py
- src/workers/config_processor.py
- src/workers/worker_tile_processor.py
- tests/test_umep_processing.py
See https://gfw.atlassian.net/browse/CDB-320
> Cdb 320 add option for post processing clipping of mrt results in c tcm

- src/worker_manager/ancillary_files.py
- src/workers/city_data.py
See https://gfw.atlassian.net/browse/CDB-399
> Cdb 399 enable half hour utc offsets

- environment.yml
Added pydantic package to environment.yml
> added mising package needed by UMEP

- src/workers/source_cif_data_downloader.py
- tests/complex_model_suite/test_upenn_processing.py
See https://gfw.atlassian.net/browse/CDB-442
1. Added retry loops for layer downloads with initial assumptions for configuration values.
2. Increased random time offsets between downloads in attempt to avoid conflicts.
3. Fixed error in test
> added retry for layer download

- data/support/update_config_method_parameters_yml.py
> minor update to conversion script:

- data/sample_cities/ZZZ_template_city/run_b_CTCM_processing.sh
- src/worker_manager/job_manager.py
- src/workers/model_upenn/aspect_height.py
- src/workers/model_upenn/svfsCalculator_veg.py
> Cdb 458 improve ctcm ux on linux

- src/worker_manager/job_manager.py
- src/worker_manager/tools.py
- src/workers/city_data.py
- src/workers/model_upenn/svfsCalculator_veg.py
- src/workers/model_upenn/upenn_module_processor.py
- src/workers/model_upenn/weather_meanRadiantT.py
- src/workers/worker_dao.py
1. fixed bug in determination of subfolders in s3.
2. improved messages
> fixed bug in getting existing S3 subfolders and improved user messages
